
package com.mycompany.todolist;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.awt.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Muhammad Rafay
 */
public class AssignTask extends javax.swing.JFrame {

    /**
     * Creates new form AssignTask
     */
    String username;
    
    public AssignTask(String username) {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Set the location of the JFrame in the center of the screen
        setLocation((screenSize.width - getWidth()) / 2,
                           (screenSize.height - getHeight()) / 2);
        ErrorText.setHorizontalAlignment(ErrorText.CENTER);
        
        this.username=username;
        
       
        try{
            
            Conn c= new Conn();
            
            String query= "select username from signup";
            
            AssignToCombo.removeAllItems();
            
            ResultSet rs= c.s.executeQuery(query);
            
             while (rs.next()) {
            String user = rs.getString("username");
            AssignToCombo.addItem(user);
            
            AssignToCombo.removeItem(username);
        }
        }
        catch(Exception e){
            System.out.println(e);
             }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpPane = new javax.swing.JPanel();
        TaskNameLabel = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        Taskname = new javax.swing.JTextField();
        AddTaskButton = new javax.swing.JButton();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        TaskDescriptionLabel = new javax.swing.JLabel();
        AssignToCombo = new javax.swing.JComboBox<>();
        ErrorText = new javax.swing.JLabel();
        DateTimeField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SignUpPane.setBackground(new java.awt.Color(204, 204, 255));
        SignUpPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 8, true));

        TaskNameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TaskNameLabel.setText("Task Name");

        PasswordLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        PasswordLabel2.setText("Due Date/Time");

        Taskname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Taskname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Taskname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TasknameActionPerformed(evt);
            }
        });

        AddTaskButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        AddTaskButton.setText("Add Task!");
        AddTaskButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AddTaskButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskButtonActionPerformed(evt);
            }
        });

        ConfirmPasswordLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ConfirmPasswordLabel.setText("Assign to:");

        TaskDescriptionLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TaskDescriptionLabel.setText("Task Description");

        AssignToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "self", " " }));
        AssignToCombo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AssignToCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignToComboActionPerformed(evt);
            }
        });

        ErrorText.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        ErrorText.setForeground(new java.awt.Color(255, 0, 0));
        ErrorText.setAlignmentX(6.0F);

        DateTimeField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        DescriptionField.setColumns(20);
        DescriptionField.setRows(5);
        DescriptionField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout SignUpPaneLayout = new javax.swing.GroupLayout(SignUpPane);
        SignUpPane.setLayout(SignUpPaneLayout);
        SignUpPaneLayout.setHorizontalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordLabel2)
                            .addComponent(TaskNameLabel)
                            .addComponent(ConfirmPasswordLabel)
                            .addComponent(TaskDescriptionLabel)
                            .addComponent(Taskname)
                            .addComponent(DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(DateTimeField)
                            .addComponent(AssignToCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignUpPaneLayout.setVerticalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TaskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Taskname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(PasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DateTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AssignToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SignUpPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TasknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TasknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TasknameActionPerformed

    private void AddTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskButtonActionPerformed
        // TODO add your handling code here:

        String taskname= Taskname.getText();
        String dis= DescriptionField.getText();
        String dueDate= DateTimeField.getText();
        String assignedTo= AssignToCombo.getItemAt(0);

        if(taskname.isEmpty()){

            ErrorText.setText("Enter a Task Name!");
        }
        else if(dis.isEmpty()){
            ErrorText.setText("Enter a Description for the Task!");
        }
        else if(dueDate.isEmpty()){

            ErrorText.setText("Enter a Date/Time for task completion!");
        }
        else if(assignedTo==null){
            
            ErrorText.setText("Choose a user to assign task !");
        }
        else{
            try{
                Conn c= new Conn();
                String query = "insert into task values('"+assignedTo+"', '"+taskname+"', '"+dis+"', '"+dueDate+"','"+username+"')";
                c.s.executeUpdate(query);

                setVisible(false);
                new HomePage(username).setVisible(true);
            }
            catch(Exception e){
                System.out.println(e);
            }

        }

    }//GEN-LAST:event_AddTaskButtonActionPerformed

    private void AssignToComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignToComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignToComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskButton;
    private javax.swing.JComboBox<String> AssignToCombo;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JTextField DateTimeField;
    private javax.swing.JTextArea DescriptionField;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JPanel SignUpPane;
    private javax.swing.JLabel TaskDescriptionLabel;
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JTextField Taskname;
    // End of variables declaration//GEN-END:variables
}
