
package com.mycompany.todolist;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.*;


 
  
   
 

public class HomePage extends javax.swing.JFrame {

    ImageIcon i1= new ImageIcon(ClassLoader.getSystemResource("./icons/user.png"));
    Image i2= i1.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT);
    ImageIcon i3 = new ImageIcon(i2);

    
    String username;
   int top;
   int top2;
   Tasks[] task;
   Tasks[] assignedtask;
   
   javax.swing.JPanel[] Tasks = new javax.swing.JPanel[8];
   javax.swing.JLabel[] TaskNames = new javax.swing.JLabel[8];
   javax.swing.JLabel[] TaskDates= new javax.swing.JLabel[8];
   javax.swing.JLabel[] Assigned= new javax.swing.JLabel[8];
   String[] discriptions= new String[8];
   String assignedBy;
   
    /**
     * Creates new form HomePage
     */
    public HomePage(String username) {
        this.username=username;
        this.top=-1;
         this.top2=-1;
        initComponents();
        
        this.Tasks = new javax.swing.JPanel[]{Task1, Task2, Task3, Task4, Task5, Task6, Task7, Task8};
        this.TaskNames=  new javax.swing.JLabel[]{task1name,task2name,task3name,task4name,task5name,task6name,task7name,task8name};
        this.TaskDates=  new javax.swing.JLabel[]{TaskDate,TaskDate1,TaskDate2,TaskDate3,TaskDate4,TaskDate5,TaskDate6,TaskDate7};
        this.Assigned=  new javax.swing.JLabel[]{AssignedBy,AssignedBy1,AssignedBy2,AssignedBy3,AssignedBy4,AssignedBy5,AssignedBy6,AssignedBy7};

      
               Tasks[0].setVisible(false);
               Tasks[1].setVisible(false);
               Tasks[2].setVisible(false);
               Tasks[3].setVisible(false);
               Tasks[4].setVisible(false);
               Tasks[5].setVisible(false);
               Tasks[6].setVisible(false);
               Tasks[7].setVisible(false);
               
                TaskDone.setVisible(true);
        TaskDone1.setVisible(true);
        TaskDone2.setVisible(true);
        TaskDone3.setVisible(true);
        TaskDone4.setVisible(true);
        TaskDone5.setVisible(true);
        TaskDone6.setVisible(true);
        TaskDone7.setVisible(true);
               
               try{
            
            Conn c= new Conn();
            
            String query= "select * from task where assignedTo = '"+username+"'";
            
            
            ResultSet rs= c.s.executeQuery(query);
           

            
             while (rs.next()) {
                 
            String taskname = rs.getString("taskname");
            String taskdis = rs.getString("taskdis");
            String taskdatetime= rs.getString("taskdatetime");
            assignedBy = rs.getString("assignedBy");
            String assignedTo = rs.getString("assignedTo");
            
            
                 
            
            
            Tasks[++top].setVisible(true);
            TaskNames[top].setText(taskname);
            TaskDates[top].setText("Due Date/time: "+taskdatetime);
            Assigned[top].setText("Assigned By: "+assignedBy);
            discriptions[top]=taskdis;
            
        }
        }
        catch(Exception e){
            System.out.println(e);
        }
               
                
        // Get the screen size
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Set the location of the JFrame in the center of the screen
        setLocation((screenSize.width - getWidth()) / 2,
                           (screenSize.height - getHeight()) / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPagePane = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        welcomeAndFormSeperator = new javax.swing.JSeparator();
        FooterPanel = new javax.swing.JPanel();
        FooterLabel = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel(i3);
        Nav = new javax.swing.JPanel();
        PersonalTasks = new javax.swing.JButton();
        AssignedTasks = new javax.swing.JButton();
        AddTask = new javax.swing.JButton();
        AssignTask = new javax.swing.JButton();
        Task1 = new javax.swing.JPanel();
        TaskDone = new javax.swing.JButton();
        TaskDate = new javax.swing.JLabel();
        task1name = new javax.swing.JLabel();
        AssignedBy = new javax.swing.JLabel();
        Info = new javax.swing.JButton();
        Task2 = new javax.swing.JPanel();
        TaskDone1 = new javax.swing.JButton();
        TaskDate1 = new javax.swing.JLabel();
        task2name = new javax.swing.JLabel();
        AssignedBy1 = new javax.swing.JLabel();
        Info1 = new javax.swing.JButton();
        Task3 = new javax.swing.JPanel();
        TaskDone2 = new javax.swing.JButton();
        TaskDate2 = new javax.swing.JLabel();
        task3name = new javax.swing.JLabel();
        AssignedBy2 = new javax.swing.JLabel();
        Info2 = new javax.swing.JButton();
        Task4 = new javax.swing.JPanel();
        TaskDone3 = new javax.swing.JButton();
        TaskDate3 = new javax.swing.JLabel();
        task4name = new javax.swing.JLabel();
        AssignedBy3 = new javax.swing.JLabel();
        Info3 = new javax.swing.JButton();
        Task5 = new javax.swing.JPanel();
        TaskDone4 = new javax.swing.JButton();
        TaskDate4 = new javax.swing.JLabel();
        task5name = new javax.swing.JLabel();
        AssignedBy4 = new javax.swing.JLabel();
        Info4 = new javax.swing.JButton();
        Task6 = new javax.swing.JPanel();
        TaskDone5 = new javax.swing.JButton();
        TaskDate5 = new javax.swing.JLabel();
        task6name = new javax.swing.JLabel();
        AssignedBy5 = new javax.swing.JLabel();
        Info5 = new javax.swing.JButton();
        Task7 = new javax.swing.JPanel();
        TaskDone6 = new javax.swing.JButton();
        TaskDate6 = new javax.swing.JLabel();
        task7name = new javax.swing.JLabel();
        AssignedBy6 = new javax.swing.JLabel();
        Info6 = new javax.swing.JButton();
        Task8 = new javax.swing.JPanel();
        TaskDone7 = new javax.swing.JButton();
        TaskDate7 = new javax.swing.JLabel();
        task8name = new javax.swing.JLabel();
        AssignedBy7 = new javax.swing.JLabel();
        Info7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPagePane.setBackground(new java.awt.Color(253, 242, 255));
        loginPagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        WelcomeLabel.setFont(new java.awt.Font("Times New Roman", 0, 72)); // NOI18N
        WelcomeLabel.setText("TODO LIST");

        welcomeAndFormSeperator.setForeground(new java.awt.Color(0, 0, 0));

        FooterPanel.setBackground(new java.awt.Color(0, 0, 0));

        FooterLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        FooterLabel.setText("© TODO LIST APP BY SHAFAY");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FooterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(392, 392, 392))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FooterLabel)
                .addContainerGap())
        );

        userIcon.setBackground(new java.awt.Color(255, 255, 255));
        userIcon.setText(username);
        userIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        userIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userIcon.setMaximumSize(new java.awt.Dimension(72, 30));
        userIcon.setMinimumSize(new java.awt.Dimension(72, 30));
        userIcon.setPreferredSize(new java.awt.Dimension(150, 50));
        userIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userIconMouseExited(evt);
            }
        });

        Nav.setBackground(new java.awt.Color(255, 255, 255));

        PersonalTasks.setBackground(new java.awt.Color(204, 204, 255));
        PersonalTasks.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        PersonalTasks.setText("Personal Tasks");
        PersonalTasks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        PersonalTasks.setPreferredSize(new java.awt.Dimension(151, 32));
        PersonalTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PersonalTasksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PersonalTasksMouseExited(evt);
            }
        });
        PersonalTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalTasksActionPerformed(evt);
            }
        });

        AssignedTasks.setBackground(new java.awt.Color(255, 255, 251));
        AssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AssignedTasks.setText("Assigned Tasks");
        AssignedTasks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        AssignedTasks.setMinimumSize(new java.awt.Dimension(151, 32));
        AssignedTasks.setPreferredSize(new java.awt.Dimension(151, 33));
        AssignedTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssignedTasksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssignedTasksMouseExited(evt);
            }
        });
        AssignedTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignedTasksActionPerformed(evt);
            }
        });

        AddTask.setBackground(new java.awt.Color(255, 255, 251));
        AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddTask.setText("Add Task!");
        AddTask.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        AddTask.setMinimumSize(new java.awt.Dimension(151, 32));
        AddTask.setPreferredSize(new java.awt.Dimension(151, 33));
        AddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddTaskMouseExited(evt);
            }
        });
        AddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskActionPerformed(evt);
            }
        });

        AssignTask.setBackground(new java.awt.Color(255, 255, 251));
        AssignTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AssignTask.setText("Assign Task!");
        AssignTask.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        AssignTask.setMinimumSize(new java.awt.Dimension(151, 32));
        AssignTask.setPreferredSize(new java.awt.Dimension(151, 33));
        AssignTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssignTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssignTaskMouseExited(evt);
            }
        });
        AssignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(PersonalTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(AssignedTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(AddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssignTask, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AssignedTasks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AssignTask, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PersonalTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Task1.setBackground(new java.awt.Color(255, 255, 255));
        Task1.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone.setText("DONE ✔ ");
        TaskDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDoneActionPerformed(evt);
            }
        });

        TaskDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate.setText("Due Date: ");

        task1name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        task1name.setText("Task one ");

        AssignedBy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy.setText("Assigned By:");

        Info.setText("INFO!");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task1Layout = new javax.swing.GroupLayout(Task1);
        Task1.setLayout(Task1Layout);
        Task1Layout.setHorizontalGroup(
            Task1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task1name, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info)
                .addGap(18, 18, 18)
                .addComponent(TaskDone)
                .addGap(18, 18, 18))
        );
        Task1Layout.setVerticalGroup(
            Task1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Task1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Task1Layout.createSequentialGroup()
                        .addGroup(Task1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TaskDate)
                            .addComponent(task1name)
                            .addComponent(AssignedBy))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaskDone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Task2.setBackground(new java.awt.Color(255, 255, 255));
        Task2.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone1.setText("DONE ✔ ");
        TaskDone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone1ActionPerformed(evt);
            }
        });

        TaskDate1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate1.setText("Due Date: ");

        task2name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task2name.setText("Task Two");

        AssignedBy1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy1.setText("Assigned By:");

        Info1.setText("INFO!");
        Info1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task2Layout = new javax.swing.GroupLayout(Task2);
        Task2.setLayout(Task2Layout);
        Task2Layout.setHorizontalGroup(
            Task2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task2name, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info1)
                .addGap(18, 18, 18)
                .addComponent(TaskDone1)
                .addGap(18, 18, 18))
        );
        Task2Layout.setVerticalGroup(
            Task2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Task2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskDone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Task2Layout.createSequentialGroup()
                        .addComponent(TaskDate1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Info1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(Task2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignedBy1)
                    .addComponent(task2name))
                .addGap(15, 15, 15))
        );

        Task3.setBackground(new java.awt.Color(255, 255, 255));
        Task3.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone2.setText("DONE ✔ ");
        TaskDone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone2ActionPerformed(evt);
            }
        });

        TaskDate2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate2.setText("Due Date: ");

        task3name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task3name.setText("Task three");

        AssignedBy2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy2.setText("Assigned By:");

        Info2.setText("INFO!");
        Info2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task3Layout = new javax.swing.GroupLayout(Task3);
        Task3.setLayout(Task3Layout);
        Task3Layout.setHorizontalGroup(
            Task3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task3name, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info2)
                .addGap(18, 18, 18)
                .addComponent(TaskDone2)
                .addGap(18, 18, 18))
        );
        Task3Layout.setVerticalGroup(
            Task3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Task3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskDone2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(Task3Layout.createSequentialGroup()
                        .addComponent(TaskDate2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Info2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Task3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignedBy2)
                    .addComponent(task3name))
                .addGap(15, 15, 15))
        );

        Task4.setBackground(new java.awt.Color(255, 255, 255));
        Task4.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone3.setText("DONE ✔ ");
        TaskDone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone3ActionPerformed(evt);
            }
        });

        TaskDate3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate3.setText("Due Date: ");

        task4name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task4name.setText("Task four");

        AssignedBy3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy3.setText("Assigned By:");

        Info3.setText("INFO!");
        Info3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task4Layout = new javax.swing.GroupLayout(Task4);
        Task4.setLayout(Task4Layout);
        Task4Layout.setHorizontalGroup(
            Task4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task4name, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info3)
                .addGap(18, 18, 18)
                .addComponent(TaskDone3)
                .addGap(18, 18, 18))
        );
        Task4Layout.setVerticalGroup(
            Task4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(Task4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Task4Layout.createSequentialGroup()
                        .addComponent(TaskDate3)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(Task4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(Task4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Info3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TaskDone3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Task4Layout.createSequentialGroup()
                                .addGroup(Task4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AssignedBy3)
                                    .addComponent(task4name))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        Task5.setBackground(new java.awt.Color(255, 255, 255));
        Task5.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone4.setText("DONE ✔ ");
        TaskDone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone4ActionPerformed(evt);
            }
        });

        TaskDate4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate4.setText("Due Date: ");

        task5name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task5name.setText("Task five");

        AssignedBy4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy4.setText("Assigned By:");

        Info4.setText("INFO!");
        Info4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task5Layout = new javax.swing.GroupLayout(Task5);
        Task5.setLayout(Task5Layout);
        Task5Layout.setHorizontalGroup(
            Task5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task5name, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info4)
                .addGap(18, 18, 18)
                .addComponent(TaskDone4)
                .addGap(18, 18, 18))
        );
        Task5Layout.setVerticalGroup(
            Task5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Task5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Task5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TaskDone4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Info4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Task5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TaskDate4)
                        .addComponent(AssignedBy4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(task5name)
                .addGap(16, 16, 16))
        );

        Task6.setBackground(new java.awt.Color(255, 255, 255));
        Task6.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone5.setText("DONE ✔ ");
        TaskDone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone5ActionPerformed(evt);
            }
        });

        TaskDate5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate5.setText("Due Date: ");

        task6name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task6name.setText("Task six");

        AssignedBy5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy5.setText("Assigned By:");

        Info5.setText("INFO!");
        Info5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task6Layout = new javax.swing.GroupLayout(Task6);
        Task6.setLayout(Task6Layout);
        Task6Layout.setHorizontalGroup(
            Task6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(task6name, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedBy5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info5)
                .addGap(18, 18, 18)
                .addComponent(TaskDone5)
                .addGap(18, 18, 18))
        );
        Task6Layout.setVerticalGroup(
            Task6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Task6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Task6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(task6name)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Task6Layout.createSequentialGroup()
                        .addGroup(Task6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TaskDone5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addGroup(Task6Layout.createSequentialGroup()
                                .addGroup(Task6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AssignedBy5)
                                    .addComponent(TaskDate5))
                                .addGap(0, 19, Short.MAX_VALUE))
                            .addComponent(Info5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        Task7.setBackground(new java.awt.Color(255, 255, 255));
        Task7.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone6.setText("DONE ✔ ");
        TaskDone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone6ActionPerformed(evt);
            }
        });

        TaskDate6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate6.setText("Due Date: ");

        task7name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task7name.setText("Task seven");

        AssignedBy6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy6.setText("Assigned By:");

        Info6.setText("INFO!");
        Info6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task7Layout = new javax.swing.GroupLayout(Task7);
        Task7.setLayout(Task7Layout);
        Task7Layout.setHorizontalGroup(
            Task7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(task7name, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AssignedBy6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info6)
                .addGap(18, 18, 18)
                .addComponent(TaskDone6)
                .addGap(18, 18, 18))
        );
        Task7Layout.setVerticalGroup(
            Task7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task7Layout.createSequentialGroup()
                .addGroup(Task7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Task7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Task7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AssignedBy6)
                            .addComponent(TaskDate6))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Task7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TaskDone6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(Info6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(task7name)
                .addGap(14, 14, 14))
        );

        Task8.setBackground(new java.awt.Color(255, 255, 255));
        Task8.setForeground(new java.awt.Color(255, 255, 255));

        TaskDone7.setText("DONE ✔ ");
        TaskDone7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskDone7ActionPerformed(evt);
            }
        });

        TaskDate7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TaskDate7.setText("Due Date: ");

        task8name.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        task8name.setText("Task Eight");

        AssignedBy7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignedBy7.setText("Assigned By:");

        Info7.setText("INFO!");
        Info7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Info7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Task8Layout = new javax.swing.GroupLayout(Task8);
        Task8.setLayout(Task8Layout);
        Task8Layout.setHorizontalGroup(
            Task8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(task8name, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AssignedBy7, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaskDate7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Info7)
                .addGap(18, 18, 18)
                .addComponent(TaskDone7)
                .addGap(18, 18, 18))
        );
        Task8Layout.setVerticalGroup(
            Task8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Task8Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(Task8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Task8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Info7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(TaskDate7)
                        .addComponent(AssignedBy7)
                        .addComponent(task8name))
                    .addComponent(TaskDone7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout loginPagePaneLayout = new javax.swing.GroupLayout(loginPagePane);
        loginPagePane.setLayout(loginPagePaneLayout);
        loginPagePaneLayout.setHorizontalGroup(
            loginPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPagePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeLabel)
                .addGap(160, 160, 160)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPagePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeAndFormSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPagePaneLayout.setVerticalGroup(
            loginPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPagePaneLayout.createSequentialGroup()
                .addGroup(loginPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPagePaneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPagePaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeAndFormSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Task1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(FooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 boolean isFull(){
       
       return top== task.length-1;
   }
 
  boolean isFull2(){
       
       return top2== task.length-1;
   }
   
   boolean isEmpty(){
       
       return top==-1 ;
   }

    private void AssignedTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignedTasksActionPerformed
        // TODO add your handling code here:

AssignedTasks.setBackground(new java.awt.Color(204, 204, 255));

AssignedTasks.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N

AssignedTasks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

AssignedTasks.setPreferredSize(new java.awt.Dimension(151, 32));

PersonalTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

PersonalTasks.setBackground(new java.awt.Color(255,255,255));

AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AddTask.setBackground(new java.awt.Color(255,255,255));

AssignTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignTask.setBackground(new java.awt.Color(255,255,255));

AssignedTasks.setMinimumSize(new java.awt.Dimension(151, 32));

AssignedTasks.setPreferredSize(new java.awt.Dimension(151, 33));

                Tasks[0]= Task1;
                Tasks[1]= Task2;
                Tasks[2]= Task3;
                Tasks[3]= Task4;
                Tasks[4]= Task5;
                Tasks[5]= Task6;
                Tasks[6]= Task7;
                Tasks[7]= Task8;

               Task1.setVisible(false);
               Task2.setVisible(false);
               Task3.setVisible(false);
               Task4.setVisible(false);
               Task5.setVisible(false);
               Task6.setVisible(false);
               Task7.setVisible(false);
               Task8.setVisible(false);

        TaskDone.setVisible(false);
        TaskDone1.setVisible(false);
        TaskDone2.setVisible(false);
        TaskDone3.setVisible(false);
        TaskDone4.setVisible(false);
        TaskDone5.setVisible(false);
        TaskDone6.setVisible(false);
        TaskDone7.setVisible(false);
        
         try{
            
            Conn c= new Conn();
            
            String query= "select * from task where assignedBy = '"+username+"' and assignedTo != '"+username+"'";
            
            ResultSet rs= c.s.executeQuery(query);
           
            top2=-1;
            
             while (rs.next()) {
                 
            String taskname = rs.getString("taskname");
            String taskdis = rs.getString("taskdis");
            String taskdatetime= rs.getString("taskdatetime");
            assignedBy = rs.getString("assignedBy");
            String assignedTo = rs.getString("assignedTo");
            
            
            Tasks[++top2].setVisible(true);
            TaskNames[top2].setText(taskname);
            TaskDates[top2].setText("Due Date/time: "+taskdatetime);
            Assigned[top2].setText("Assigned To: "+assignedTo);
            discriptions[top2]=taskdis;
            
        }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_AssignedTasksActionPerformed

    private void PersonalTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalTasksActionPerformed
PersonalTasks.setBackground(new java.awt.Color(204, 204, 255));

PersonalTasks.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N

PersonalTasks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

PersonalTasks.setPreferredSize(new java.awt.Dimension(151, 32));

AssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignedTasks.setBackground(new java.awt.Color(255,255,255));

AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AddTask.setBackground(new java.awt.Color(255,255,255));

AssignTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignTask.setBackground(new java.awt.Color(255,255,255));

PersonalTasks.setMinimumSize(new java.awt.Dimension(151, 32));

PersonalTasks.setPreferredSize(new java.awt.Dimension(151, 33));      

            setVisible(false);
            new  HomePage(username).setVisible(true);
          

    }//GEN-LAST:event_PersonalTasksActionPerformed

    private void AssignedTasksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignedTasksMouseEntered
        // TODO add your handling code here:
        AssignedTasks.setFont(new java.awt.Font("Segoe UI", 3, 18));
        
    }//GEN-LAST:event_AssignedTasksMouseEntered

    private void AssignedTasksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignedTasksMouseExited
        // TODO add your handling code here:
        AssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    }//GEN-LAST:event_AssignedTasksMouseExited

    private void PersonalTasksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalTasksMouseEntered
        // TODO add your handling code here:
        PersonalTasks.setFont(new java.awt.Font("Segoe UI", 3, 18));
    }//GEN-LAST:event_PersonalTasksMouseEntered

    private void PersonalTasksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalTasksMouseExited
        // TODO add your handling code here:
        PersonalTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    }//GEN-LAST:event_PersonalTasksMouseExited

    private void AddTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMouseEntered
        // TODO add your handling code here:
        AddTask.setFont(new java.awt.Font("Segoe UI", 3, 18));
    }//GEN-LAST:event_AddTaskMouseEntered

    private void AddTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTaskMouseExited
        // TODO add your handling code here:
        AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    }//GEN-LAST:event_AddTaskMouseExited

    private void AddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskActionPerformed
        // TODO add your handling code here:
AddTask.setBackground(new java.awt.Color(204, 204, 255));

AddTask.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N

AddTask.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

AddTask.setPreferredSize(new java.awt.Dimension(151, 32));

AddTask.setMinimumSize(new java.awt.Dimension(151, 32));

AddTask.setPreferredSize(new java.awt.Dimension(151, 33)); 

AssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignedTasks.setBackground(new java.awt.Color(255,255,255));

AssignTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignTask.setBackground(new java.awt.Color(255,255,255));

PersonalTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

PersonalTasks.setBackground(new java.awt.Color(255,255,255));

if(isFull())
{
    JOptionPane.showMessageDialog(null,"LIST IS FULL, PLEASE REMOVE A PENDING TASK FIRST!");
 
    }//GEN-LAST:event_AddTaskActionPerformed

else{
        setVisible(false);
        new NewTask(username).setVisible(true);
    }
}
    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        // TODO add your handling code here:
        
        new TaskDiscription(TaskNames[0].getText(),discriptions[0],Assigned[0].getText(),TaskDates[0].getText()).setVisible(true);
    }//GEN-LAST:event_InfoActionPerformed

    private void Info1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info1ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[1].getText(),discriptions[1],Assigned[1].getText(),TaskDates[1].getText()).setVisible(true);
    }//GEN-LAST:event_Info1ActionPerformed

    private void Info2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info2ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[2].getText(),discriptions[2],Assigned[2].getText(),TaskDates[2].getText()).setVisible(true);
    }//GEN-LAST:event_Info2ActionPerformed

    private void Info3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info3ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[3].getText(),discriptions[3],Assigned[3].getText(),TaskDates[3].getText()).setVisible(true);
    }//GEN-LAST:event_Info3ActionPerformed

    private void Info4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info4ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[4].getText(),discriptions[4],Assigned[4].getText(),TaskDates[4].getText()).setVisible(true);
    }//GEN-LAST:event_Info4ActionPerformed

    private void Info5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info5ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[5].getText(),discriptions[5],Assigned[5].getText(),TaskDates[5].getText()).setVisible(true);
    }//GEN-LAST:event_Info5ActionPerformed

    private void Info6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info6ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[6].getText(),discriptions[6],Assigned[6].getText(),TaskDates[6].getText()).setVisible(true);
    }//GEN-LAST:event_Info6ActionPerformed

    private void Info7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Info7ActionPerformed
        // TODO add your handling code here:
        new TaskDiscription(TaskNames[7].getText(),discriptions[7],Assigned[7].getText(),TaskDates[7].getText()).setVisible(true);
    }//GEN-LAST:event_Info7ActionPerformed

    private void AssignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignTaskActionPerformed
        // TODO add your handling code here:
        AddTask.setBackground(new java.awt.Color(204, 204, 255));

AssignTask.setFont(new java.awt.Font("Segoe UI", 3, 21)); // NOI18N

AssignTask.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(0, 0, 0)));

AssignTask.setPreferredSize(new java.awt.Dimension(151, 32));

AssignTask.setMinimumSize(new java.awt.Dimension(151, 32));

AssignTask.setPreferredSize(new java.awt.Dimension(151, 33)); 

AssignedTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AssignedTasks.setBackground(new java.awt.Color(255,255,255));

AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

AddTask.setBackground(new java.awt.Color(255,255,255));

PersonalTasks.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

PersonalTasks.setBackground(new java.awt.Color(255,255,255));

if(isFull2())
{
    JOptionPane.showMessageDialog(null,"LIST IS FULL, PLEASE REMOVE A PENDING TASK FIRST!");
 
    }                                       

else{
        setVisible(false);
        new AssignTask(username).setVisible(true);
    }
    }//GEN-LAST:event_AssignTaskActionPerformed

    private void AssignTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignTaskMouseEntered
        // TODO add your handling code here:
         AssignTask.setFont(new java.awt.Font("Segoe UI", 3, 18));
    }//GEN-LAST:event_AssignTaskMouseEntered

    private void AssignTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignTaskMouseExited
        
        AddTask.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    }//GEN-LAST:event_AssignTaskMouseExited

    private void TaskDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDoneActionPerformed
        Tasks[0].setVisible(false);
        pop(0, task1name.getText());
        
    }//GEN-LAST:event_TaskDoneActionPerformed

    private void TaskDone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone1ActionPerformed
        
        Tasks[1].setVisible(false);
       pop(1, task2name.getText());
      
    }//GEN-LAST:event_TaskDone1ActionPerformed

    private void TaskDone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone2ActionPerformed
         Tasks[2].setVisible(false);
          pop(2,task3name.getText());
       
    }//GEN-LAST:event_TaskDone2ActionPerformed

    private void TaskDone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone3ActionPerformed
         Tasks[3].setVisible(false);
        pop(3,task4name.getText());
       
    }//GEN-LAST:event_TaskDone3ActionPerformed

    private void TaskDone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone4ActionPerformed
        Tasks[4].setVisible(false);
       pop(4,task5name.getText());
      
    }//GEN-LAST:event_TaskDone4ActionPerformed

    private void TaskDone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone5ActionPerformed
        Tasks[5].setVisible(false);
        pop(5,task6name.getText());
    }//GEN-LAST:event_TaskDone5ActionPerformed

    private void TaskDone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone6ActionPerformed
        Tasks[6].setVisible(false);
        pop(6,task7name.getText());
    }//GEN-LAST:event_TaskDone6ActionPerformed

    private void TaskDone7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskDone7ActionPerformed
       Tasks[7].setVisible(false);
       pop(7,task8name.getText());
       
    }//GEN-LAST:event_TaskDone7ActionPerformed

    private void userIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIconMouseEntered
        // TODO add your handling code here:
      PersonalTasks.setBackground(new java.awt.Color(204, 204, 255));


userIcon.setFont(new java.awt.Font("Segoe UI", 3, 21));

    }//GEN-LAST:event_userIconMouseEntered

    private void userIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIconMouseExited

        userIcon.setBackground(new java.awt.Color(255, 255, 255));
        userIcon.setFont(new java.awt.Font("Segoe UI", 3, 15));

        // TODO add your handling code here:
    }//GEN-LAST:event_userIconMouseExited

    private void userIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIconMouseClicked
        // TODO add your handling code here:
        new userDeets(username).setVisible(true);
    }//GEN-LAST:event_userIconMouseClicked

   private void pop(int index, String text) {
    try {
        Conn c = new Conn();
        String query = "DELETE FROM task WHERE taskname = '" + text + "'";
        c.s.executeUpdate(query);
    } catch (Exception e) {
        System.out.println(e);
    }
    
 Tasks=newArrayAfterRemoving(Tasks[index]);
   

} 
    javax.swing.JPanel[] newArrayAfterRemoving(javax.swing.JPanel TaskToBeRemoved) {
    int newLength = Tasks.length - 1;
    javax.swing.JPanel[] newArray = new javax.swing.JPanel[newLength];

    int j = 0;
    for (int i = 0; i < Tasks.length; i++) {
        if (Tasks[i] == TaskToBeRemoved) {
            continue;
        }
        newArray[j++] = Tasks[i];
    }
        
    return newArray;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTask;
    private javax.swing.JButton AssignTask;
    private javax.swing.JLabel AssignedBy;
    private javax.swing.JLabel AssignedBy1;
    private javax.swing.JLabel AssignedBy2;
    private javax.swing.JLabel AssignedBy3;
    private javax.swing.JLabel AssignedBy4;
    private javax.swing.JLabel AssignedBy5;
    private javax.swing.JLabel AssignedBy6;
    private javax.swing.JLabel AssignedBy7;
    public javax.swing.JButton AssignedTasks;
    private javax.swing.JLabel FooterLabel;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JButton Info;
    private javax.swing.JButton Info1;
    private javax.swing.JButton Info2;
    private javax.swing.JButton Info3;
    private javax.swing.JButton Info4;
    private javax.swing.JButton Info5;
    private javax.swing.JButton Info6;
    private javax.swing.JButton Info7;
    private javax.swing.JPanel Nav;
    private javax.swing.JButton PersonalTasks;
    public javax.swing.JPanel Task1;
    public javax.swing.JPanel Task2;
    public javax.swing.JPanel Task3;
    public javax.swing.JPanel Task4;
    public javax.swing.JPanel Task5;
    public javax.swing.JPanel Task6;
    public javax.swing.JPanel Task7;
    public javax.swing.JPanel Task8;
    public javax.swing.JLabel TaskDate;
    public javax.swing.JLabel TaskDate1;
    public javax.swing.JLabel TaskDate2;
    public javax.swing.JLabel TaskDate3;
    public javax.swing.JLabel TaskDate4;
    public javax.swing.JLabel TaskDate5;
    public javax.swing.JLabel TaskDate6;
    public javax.swing.JLabel TaskDate7;
    private javax.swing.JButton TaskDone;
    private javax.swing.JButton TaskDone1;
    private javax.swing.JButton TaskDone2;
    private javax.swing.JButton TaskDone3;
    private javax.swing.JButton TaskDone4;
    private javax.swing.JButton TaskDone5;
    private javax.swing.JButton TaskDone6;
    private javax.swing.JButton TaskDone7;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JPanel loginPagePane;
    private javax.swing.JLabel task1name;
    private javax.swing.JLabel task2name;
    private javax.swing.JLabel task3name;
    private javax.swing.JLabel task4name;
    private javax.swing.JLabel task5name;
    private javax.swing.JLabel task6name;
    private javax.swing.JLabel task7name;
    private javax.swing.JLabel task8name;
    private javax.swing.JLabel userIcon;
    private javax.swing.JSeparator welcomeAndFormSeperator;
    // End of variables declaration//GEN-END:variables
}
