
package com.mycompany.todolist;

import java.awt.Dimension;
import java.awt.Toolkit;


public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUpJframe
     */
    public SignUp() {
        initComponents();
        // Get the screen size
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Set the location of the JFrame in the center of the screen
        setLocation((screenSize.width - getWidth()) / 2,
                           (screenSize.height - getHeight()) / 2);
        ErrorText.setHorizontalAlignment(ErrorText.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpPagePane = new javax.swing.JPanel();
        WelcomeLabel2 = new javax.swing.JLabel();
        welcomeAndFormSeperator2 = new javax.swing.JSeparator();
        SignUpPane = new javax.swing.JPanel();
        UsernameLabel2 = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        ErrorText = new javax.swing.JLabel();
        FooterPanel = new javax.swing.JPanel();
        FooterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SignUpPagePane.setBackground(new java.awt.Color(251, 242, 255));
        SignUpPagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        WelcomeLabel2.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        WelcomeLabel2.setText("SIGN UP");

        welcomeAndFormSeperator2.setForeground(new java.awt.Color(0, 0, 0));

        SignUpPane.setBackground(new java.awt.Color(204, 204, 255));

        UsernameLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        UsernameLabel2.setText("Username");

        PasswordLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        PasswordLabel2.setText("Password");

        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SignUpButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        SignUpButton.setText("CREATE ACCOUNT!");
        SignUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        ConfirmPasswordLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ConfirmPasswordLabel.setText("Confirm Password");

        ConfirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EmailLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        ErrorText.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        ErrorText.setForeground(new java.awt.Color(255, 0, 0));
        ErrorText.setAlignmentX(6.0F);

        javax.swing.GroupLayout SignUpPaneLayout = new javax.swing.GroupLayout(SignUpPane);
        SignUpPane.setLayout(SignUpPaneLayout);
        SignUpPaneLayout.setHorizontalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SignUpPaneLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignUpPaneLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordLabel2)
                                    .addComponent(UsernameLabel2)
                                    .addComponent(Username)
                                    .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(ConfirmPasswordLabel)
                                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(Email)
                                    .addComponent(EmailLabel))))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(ErrorText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SignUpPaneLayout.setVerticalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(UsernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        FooterPanel.setBackground(new java.awt.Color(0, 0, 0));

        FooterLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        FooterLabel.setText("© TODO LIST APP BY SHAFAY!");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FooterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FooterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SignUpPagePaneLayout = new javax.swing.GroupLayout(SignUpPagePane);
        SignUpPagePane.setLayout(SignUpPagePaneLayout);
        SignUpPagePaneLayout.setHorizontalGroup(
            SignUpPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SignUpPagePaneLayout.createSequentialGroup()
                .addGroup(SignUpPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPagePaneLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(SignUpPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignUpPagePaneLayout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(WelcomeLabel2))
                    .addGroup(SignUpPagePaneLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(welcomeAndFormSeperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        SignUpPagePaneLayout.setVerticalGroup(
            SignUpPagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPagePaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(WelcomeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeAndFormSeperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(SignUpPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(FooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignUpPagePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
       // TODO add your handling code here:
    
    String name = Username.getText();
    String email = Email.getText();
    String password = new String(Password.getPassword());
    String confPass = new String(ConfirmPassword.getPassword());
    
    if(name.isEmpty()){
        
        ErrorText.setText("Enter a Name!");
    }
    else if(email.isEmpty()){
        
        ErrorText.setText("Enter an Email!");
    }
    else if(password.isEmpty()){
        
        ErrorText.setText("Enter a Password!");
    }
    else if(!password.equals(confPass)){
        
        ErrorText.setText("Passwords dont match!");
    }
    else{
        try{
            Conn c= new Conn();
            String query = "insert into signup values('"+name+"', '"+email+"', '"+password+"')";
            String query1 = "insert into login values('"+name+"', '"+password+"')";
            c.s.executeUpdate(query);
            c.s.executeUpdate(query1);
            this.dispose();
            new CreatedPopUp(new SignUp()).setVisible(true); 
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
        
        
    }//GEN-LAST:event_SignUpButtonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JLabel FooterLabel;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpPagePane;
    private javax.swing.JPanel SignUpPane;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameLabel2;
    private javax.swing.JLabel WelcomeLabel2;
    private javax.swing.JSeparator welcomeAndFormSeperator2;
    // End of variables declaration//GEN-END:variables
}
