/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolist;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Muhammad Rafay
 */
public class userDeets extends javax.swing.JFrame {

    /**
     * Creates new form userDeets
     
    */
    String username;
    public userDeets(String username) {
        this.username=username;
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Set the location of the JFrame in the center of the screen
        setLocation((screenSize.width - getWidth()) / 2,
                           (screenSize.height - getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaskNameLabel = new javax.swing.JLabel();
        userDeetsPane = new javax.swing.JPanel();
        TaskNameLabel1 = new javax.swing.JLabel();

        TaskNameLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TaskNameLabel.setText("Task Name");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userDeetsPane.setBackground(new java.awt.Color(204, 204, 255));

        TaskNameLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TaskNameLabel1.setText(username);

        javax.swing.GroupLayout userDeetsPaneLayout = new javax.swing.GroupLayout(userDeetsPane);
        userDeetsPane.setLayout(userDeetsPaneLayout);
        userDeetsPaneLayout.setHorizontalGroup(
            userDeetsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDeetsPaneLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(TaskNameLabel1)
                .addGap(152, 152, 152))
        );
        userDeetsPaneLayout.setVerticalGroup(
            userDeetsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDeetsPaneLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(TaskNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userDeetsPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userDeetsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userDeetsPane.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TaskNameLabel;
    private javax.swing.JLabel TaskNameLabel1;
    private javax.swing.JPanel userDeetsPane;
    // End of variables declaration//GEN-END:variables
}
